print("2","+","2","=",4)
""" CLICANDO NA LINHA E ULTILIZNDO O COMANDO: CTRL + C, JÁ COPIA AUTOMTICAMENTE TODA A LINHA """

print("2","+","2","=",4, sep='-')

""" FUNÇÃO SEP='' INDICA UM NOVO SEPARADOR PARA OS ESPAÇOS OU AONDE ESTA SEPARADO"""

