# CONVERSÃO DE TIPOS 


# CONVERTENDO UMA STRING PARA UM NÚMERO
print(int('1') + 1)

# NÚMERO DA FORMA ORIGINAL, COMO NÚMERO INTERO
print(1, type(1))

# CONVERTENDO UM NÚMERO INTERO PARA UMA STRING
print(1, type(str(1)))
